### ISSUE TITLE
Question: provide underlying service client?

### ISSUE THREAD

**Issue by smacker** [bblfsh/client-go#31]
We need to call bblfsh server to get list of drivers in dashboard: https://github.com/bblfsh/dashboard/issues/89

Currently we open connection with `client-go.Client` to do all requests to the server using it and keep it open.
It sounds a little bit weird to create one more `protocol.ProtocolServiceClient` when we have one already inside `client-go.Client`.
Do you think it makes sense to add a method like
```
func(c *Client) ProtocolService() protocol.ProtocolServiceClient {}
```
?

Please share your opinion!

@abeaumont

**Comment by abeaumont** [comment]
Good question @smacker. Mixed opinions here to be honest. I think the control protocol has different requirements (since it should be used by admins, not users), so I don't think it's a good idea make the clients more complex and harderd to maintain by exposing this additional API. (I also think that this protocol has further security implications, so may evolve to have some additional authentication layer in the future, idk).

OTOH, it makes sense to know which drivers are installed, and the API exists and it's callable anyway, even if not available in the clients.

I'd like to hear what @juanjux and @mcuadros think about this too.

**Comment by smacker** [comment]
Another solution would be to create one more constructor for Client which accepts ProtocolService

**Comment by juanjux** [comment]
I like this last option (and the PR).

**Comment by abeaumont** [comment]
For me it's not a matter how to do it but whether we should do it or not, for the reasons mentioned above. If done, it should be supported in all the clients, not only this one.

**Comment by mcuadros** [comment]
I am more in using the admin API just as a plain protobuf, and keep the driver as simple as posible. The `grpc.ClientConn` can be retrieve from the `Client` so is not that bad: https://godoc.org/gopkg.in/bblfsh/client-go.v2#Client

**Comment by smacker** [comment]
@mcuadros great point. But it's kind of reversed. Creating `client-go.Client` to get `grpc.ClientConn` doesn't sound right because `grpc.ClientConn` is dependency of `client-go.Client`. And allowing to pass custom `grpc.ClientConn` also allows using [middlewares](https://github.com/grpc-ecosystem/go-grpc-middleware) which can be useful for web services

**Comment by smacker** [comment]
closed by https://github.com/bblfsh/client-go/pull/32
